package org.aksw.gwt.TripleCheckMate.shared.storage.exception;

import java.io.Serializable;

public class StorageServiceException extends Exception implements
		Serializable {

	/**
	 * Autogenerated for serialization
	 */
	private static final long serialVersionUID = -1709522630145405589L;

	private String errorMessage;

	public StorageServiceException() {
	}

	public StorageServiceException(String message) {
		this.errorMessage = message;
	}

	public String getErrorMessage() {
		return this.errorMessage;
	}

}
